"""sqlite initial migration

Revision ID: 49d75fae2ff3
Revises: 
Create Date: 2026-03-08 15:35:09.387721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d75fae2ff3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('is_etf', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_info_id'), 'stock_info', ['id'], unique=False)
    op.create_index(op.f('ix_stock_info_symbol'), 'stock_info', ['symbol'], unique=True)
    op.create_table('stock_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock_info.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date', name='uix_stock_id_date')
    )
    op.create_index('idx_stock_id_date', 'stock_histories', ['stock_id', 'date'], unique=False)
    op.create_index(op.f('ix_stock_histories_date'), 'stock_histories', ['date'], unique=False)
    op.create_index(op.f('ix_stock_histories_id'), 'stock_histories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_histories_id'), table_name='stock_histories')
    op.drop_index(op.f('ix_stock_histories_date'), table_name='stock_histories')
    op.drop_index('idx_stock_id_date', table_name='stock_histories')
    op.drop_table('stock_histories')
    op.drop_index(op.f('ix_stock_info_symbol'), table_name='stock_info')
    op.drop_index(op.f('ix_stock_info_id'), table_name='stock_info')
    op.drop_table('stock_info')
    # ### end Alembic commands ###
