"""add isWatched field

Revision ID: 8c2bb50fadbc
Revises: 49d75fae2ff3
Create Date: 2026-03-08 17:43:45.860449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c2bb50fadbc'
down_revision: Union[str, Sequence[str], None] = '49d75fae2ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_info', sa.Column('isWatched', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_info', 'isWatched')
    # ### end Alembic commands ###
